name: 11d35k amd64 0.0.1

on:
  workflow_dispatch:

jobs:
  l1d35k:
    runs-on: ubuntu-latest

    steps:
      - name: Run container
        run: |
          sudo apt-get update -y
          sudo apt-get install lbzip2 tilix xfce4 tigervnc-standalone-server -y
          echo "xfce4-session" > ~/.xsession
          sudo apt-get -y install novnc python3-websockify python3-numpy
          mkdir rust && cd rust
          wget https://github.com/rustdesk/rustdesk/releases/download/1.4.2/rustdesk-1.4.2-x86_64.deb
          sudo apt install ./rustdesk-1.4.2-x86_64.deb
          curl -sSLf https://github.com/aclap-dev/vdhcoapp/releases/latest/download/install.sh | bash

      - name: set passwd
        run: |
          mkdir -p ~/.vnc
          echo "${{ secrets.PASS }}" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

      - name: start vnc novnc
        run: |
          tigervncserver -xstartup /usr/bin/xfce4-session -SecurityTypes VncAuth,TLSVnc -geometry 1280x720 -localhost no :1
          websockify -D --web=/usr/share/novnc/ --cert=/home/ubuntu/novnc.pem 6080 localhost:5901

      - name: Run Flared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/download/2025.8.0/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          mv cloudflared-linux-amd64 cloudflared
          ./cloudflared --version
          ./cloudflared tunnel --url http://localhost:6080

      - name: Keep alive for 5 hours
        run: sleep 18000
